// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkekdbecsneymevofwsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZWtkYmVjc25leW1ldm9md3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNDMzMzQsImV4cCI6MjA3OTcxOTMzNH0.IqwRMdVJNURabFmYG6m36y01f1uUmlu0fT_V_Cm1R5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});